---
name: AppDevKit CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,OS=latest,name=iPhone 14 Pro Max
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: xcodebuild clean test -workspace AppDevKit.xcworkspace -scheme AppDevKit
          -destination "${destination}" CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}
  Pods:
    name: Cocoapods Lint (Latest Stable Xcode)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run pod lib lint
        run: pod lib lint --fail-fast --allow-warnings
